# @ref https://bazel.build/versions/master/docs/external.html

cc_binary(
    name = "drake_external",
    srcs = ["drake_external.cc"],
    deps = [
        "@drake//drake/automotive:curve2",
    ],
)
